kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
bases:
  - https://github.com/redhat-canada-gitops/catalog/rhsso/rhsso-operator/base

namespace: sso

resources:
  - namespace.yaml

patchesStrategicMerge:
  - patch-target-namespace.yaml