kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

# Remote base.  Use the configuration from the Red Hat Canada GitOps repo (unofficial).
bases:
  - github.com/redhat-canada-gitops/catalog/letsencrypt-certs/base?ref=unify

# DNS cloud credentials Sealed Secret.
resources:
  - cloud-dns-credentials-sealedsecret.json