apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: CheCluster.v1.org.eclipse.che
  name: codeready-workspaces
  namespace: codeready-workspaces
spec:
  targetNamespaces:
  - codeready-workspaces
