kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

# Namespace for Red Hat SSO operator and instance.
namespace: sso

bases:
  - ../../../../base/04-cluster-operator-instances/rhsso

resources:
  - openshift-client.yaml

# Patch the redirect URI.
#patchesJson6902:
#- target:
#    group: keycloak.org
#    version: v1alpha1
#    kind: KeycloakClient
#    name: openshift-client
#  path: patch-redirect-uri.yaml
