apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Core setup of groups, roles and bindings.
bases:
- ../../base/06-groups-roles-bindings

# Add users to argo admins group and developer group.
patchesJson6902:
- target:
    group: user.openshift.io
    version: v1
    kind: Group
    name: argocdadmins
  path: argocdadmins-group-users.yaml
- target:
    group: user.openshift.io
    version: v1
    kind: Group
    name: developer
  path: developer-group-users.yaml
